
// Auto-generated by Asset Bundle Browser — Delivery tab.
// Do not edit manually.
public static class AssetBundleName
{
    public const string Common = "common";
    public const string Shared = "shared";

    public static class Events
    {
        public const string PetalPlateParty = "events__petal_plate_party";
        public const string PizzaTowerRace = "events__pizza_tower_race";
        public const string RewardEventPopup = "events__reward_event_popup";
        public const string SpeedFeastRace = "events__speed_feast_race";
    }

    public static class Features
    {
        public const string Account = "features__account";
        public const string AvatarSelect = "features__avatar_select";
        public const string BuyCurrency = "features__buy_currency";
        public const string ChangeName = "features__change_name";
        public const string ChefsBook = "features__chefs_book";
        public const string ChoiceChest = "features__choice_chest";
        public const string ConfirmSellRareItem = "features__confirm_sell_rare_item";
        public const string DailyReward = "features__daily_reward";
        public const string HappinessExpress = "features__happiness_express";
        public const string HomeScene = "features__home_scene";
        public const string Inventory = "features__inventory";
        public const string ItemInfo = "features__item_info";
        public const string NewEquipment = "features__new_equipment";
        public const string NotEnoughCurrency = "features__not_enough_currency";
        public const string OpenStarChest = "features__open_star_chest";
        public const string OpenZoneBuildUpGoal = "features__open_zone_build_up_goal";
        public const string OrderMania = "features__order_mania";
        public const string OrderManiaReward = "features__order_mania_reward";
        public const string OverviewCanvas = "features__overview_canvas";
        public const string PopupConfirm = "features__popup_confirm";
        public const string PopupNextTheme = "features__popup_next_theme";
        public const string Rating = "features__rating";
        public const string RenovationCompleted = "features__renovation_completed";
        public const string RequireInternet = "features__require_internet";
        public const string RewardPopup = "features__reward_popup";
        public const string SaveFound = "features__save_found";
        public const string ScreenMaskChangeScene = "features__screen_mask_change_scene";
        public const string SelectLanguage = "features__select_language";
        public const string SelectTheme = "features__select_theme";
        public const string Settings = "features__settings";
        public const string Shop = "features__shop";
        public const string SoftTutItem = "features__soft_tut_item";
        public const string ToolTip = "features__tool_tip";
        public const string UnlockFeature = "features__unlock_feature";
        public const string VideoIntro = "features__video_intro";
    }

    public static class Gameplay
    {
        public const string Booster = "gameplay__booster";
        public const string ChestAndBox = "gameplay__chest_and_box";
        public const string Consumable = "gameplay__consumable";
        public const string Generators = "gameplay__generators";
        public const string Prefabs = "gameplay__prefabs";
        public const string Tools = "gameplay__tools";

        public static class ItemRaw
        {
            public const string CoconutShellProducts = "gameplay__item_raw__coconut_shell_products";
            public const string CoconutWaterProducts = "gameplay__item_raw__coconut_water_products";
            public const string Coffee = "gameplay__item_raw__coffee";
            public const string DairyProducts = "gameplay__item_raw__dairy_products";
            public const string EggAndPoultry = "gameplay__item_raw__egg_and_poultry";
            public const string Fruit = "gameplay__item_raw__fruit";
            public const string Glassware = "gameplay__item_raw__glassware";
            public const string LeafyVegetables = "gameplay__item_raw__leafy_vegetables";
            public const string RedMeat = "gameplay__item_raw__red_meat";
            public const string Seafood = "gameplay__item_raw__seafood";
            public const string Shellfish = "gameplay__item_raw__shellfish";
            public const string SoftDrinks = "gameplay__item_raw__soft_drinks";
            public const string SugarAndCandy = "gameplay__item_raw__sugar_and_candy";
            public const string Vegetables = "gameplay__item_raw__vegetables";
        }

        public static class Recipes
        {
            public const string CoffeeDrinks = "gameplay__recipes__coffee_drinks";
            public const string JamAndYogurtMix = "gameplay__recipes__jam_and_yogurt_mix";
            public const string MixedGrill = "gameplay__recipes__mixed_grill";
            public const string SmoothieAndJuice = "gameplay__recipes__smoothie_and_juice";
            public const string StirFriedDish = "gameplay__recipes__stir_fried_dish";
        }
    }

    public static class Packages
    {
        public const string BattlePass = "packages__battle_pass";
        public const string BattlePassPackage = "packages__battle_pass_package";
        public const string DiscountGemRaw = "packages__discount_gem_raw";
        public const string EnergyPack = "packages__energy_pack";
        public const string EnergyTrilogy = "packages__energy_trilogy";
        public const string HappinessExpress = "packages__happiness_express";
        public const string InfinityPack = "packages__infinity_pack";
        public const string OpenningPack = "packages__openning_pack";
        public const string PiggyBank = "packages__piggy_bank";
        public const string SpeedPackage = "packages__speed_package";
        public const string StarterPack = "packages__starter_pack";
        public const string VideoBonuses = "packages__video_bonuses";
    }

    public static class Scene
    {
        public const string Scene1 = "scene__scene_1";
        public const string Scene2 = "scene__scene_2";
        public const string Scene3 = "scene__scene_3";
        public const string Scene4 = "scene__scene_4";
        public const string Scene5 = "scene__scene_5";
    }

    public static class Tutorial
    {
        public const string Tutorials = "tutorial__tutorials";
    }
}